"""Finale version

Revision ID: 22f130ca7893
Revises: 9b62a7498995
Create Date: 2026-07-15 17:58:14.657141

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22f130ca7893"
down_revision: str | Sequence[str] | None = "9b62a7498995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.create_unique_constraint(None, "books", ["isbn"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="unique")
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    # ### end Alembic commands ###
