"""add unique constraint to order items

Revision ID: 89884a0a6d3f
Revises: 22f130ca7893
Create Date: 2026-08-13 22:42:27.941308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89884a0a6d3f"
down_revision: str | Sequence[str] | None = "22f130ca7893"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_order_item_order_book", "order_items", ["order_id", "book_id"]
    )
    op.alter_column(
        "orders",
        "total_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "total_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("uq_order_item_order_book", "order_items", type_="unique")
    # ### end Alembic commands ###
