"""Add user role

Revision ID: c00c7cbb2a9d
Revises: c09d1ba8b6da
Create Date: 2026-07-14 17:35:44.871627

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c00c7cbb2a9d"
down_revision: str | Sequence[str] | None = "c09d1ba8b6da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

user_role = sa.Enum(
    "ADMIN",
    "USER",
    name="user_role",
)


def upgrade() -> None:
    """Upgrade schema."""

    user_role.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role,
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
