"""Create table book_categories

Revision ID: 9b62a7498995
Revises: 81b052902adf
Create Date: 2026-07-14 22:18:53.865273

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b62a7498995"
down_revision: str | Sequence[str] | None = "81b052902adf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_categories",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "category_id", name="uq_book_category"),
    )
    op.create_index(
        op.f("ix_book_categories_book_id"), "book_categories", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_categories_category_id"),
        "book_categories",
        ["category_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_categories_category_id"), table_name="book_categories")
    op.drop_index(op.f("ix_book_categories_book_id"), table_name="book_categories")
    op.drop_table("book_categories")
    # ### end Alembic commands ###
